on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Write a multi-line message
      uses: actions/checkout@v3
    - name: Print Hello World
      run: |
        echo This demo file shows a 
        echo very basic and easy-to-understand workflow.
